"""
Example 10 — Latency Breakdown: TTFT and TPOT

Measures the two key latency metrics that users actually feel:

  TTFT (Time To First Token):
    Time from submit to seeing the FIRST generated byte.
    Caused by: waiting for prefill + any scheduling delay.
    Expected scaling: linear with prompt_len (more tokens → more compute).

  TPOT (Time Per Output Token):
    Average gap between successive output tokens.
    Caused by: one decode step per token.
    Expected scaling: roughly constant (memory-bound, independent of context).

Run:  python examples/10_latency_breakdown.py
"""
import sys; sys.path.insert(0, ".")
import time
import torch
from engine.llm_engine import LLMEngine
from model.config import ModelConfig, CacheConfig, SchedulerConfig, SamplingParams


class ByteTokenizer:
    vocab_size = 256
    def encode(self, t): return list(t.encode("utf-8"))
    def decode(self, ids): return bytes([max(0,min(255,i)) for i in ids]).decode("utf-8","replace")


def make_engine():
    tok = ByteTokenizer()
    mc  = ModelConfig.nano(); mc.vocab_size = tok.vocab_size
    return LLMEngine.from_config(
        mc,
        CacheConfig(block_size=16, num_gpu_blocks=512),
        SchedulerConfig(max_num_seqs=1, max_num_batched_tokens=2048),
        tok,
        device=torch.device("cuda" if torch.cuda.is_available() else "cpu"),
    )


def measure_one(prompt_len, output_len, n_runs=5):
    """Returns (ttft_ms, tpot_ms) averaged over n_runs."""
    ttfts, tpots = [], []
    for _ in range(n_runs):
        engine = make_engine()
        engine.add_request("req", "x" * prompt_len, SamplingParams(temperature=0.0, max_tokens=output_len))

        submit_t      = time.perf_counter()
        first_tok_t   = None
        tokens_so_far = 0
        last_tok_t    = submit_t

        while engine.has_unfinished_requests():
            outputs = engine.step()
            now     = time.perf_counter()
            for o in outputs:
                curr = len(o.outputs[0].token_ids)
                if curr > tokens_so_far:
                    if first_tok_t is None:
                        first_tok_t = now
                    last_tok_t    = now
                    tokens_so_far = curr

        if first_tok_t is None:
            continue
        ttft = (first_tok_t - submit_t) * 1000
        tpot = (last_tok_t - first_tok_t) / max(output_len - 1, 1) * 1000
        ttfts.append(ttft)
        tpots.append(tpot)

    return (sum(ttfts)/len(ttfts), sum(tpots)/len(tpots)) if ttfts else (0, 0)


# ── Sweep prompt length, fixed output length ───────────────────────────────────
PROMPT_LENS = [8, 16, 32, 64, 128]
OUTPUT_LEN  = 32

print("=" * 60)
print("TTFT vs Prompt Length  (output fixed at", OUTPUT_LEN, "tokens)")
print("=" * 60)
print(f"  {'Prompt':>8}  {'TTFT (ms)':>12}  {'TPOT (ms)':>12}  {'E2E (ms)':>10}")
print(f"  {'-'*50}")

for pl in PROMPT_LENS:
    ttft, tpot = measure_one(pl, OUTPUT_LEN)
    e2e = ttft + tpot * (OUTPUT_LEN - 1)
    print(f"  {pl:8d}  {ttft:12.1f}  {tpot:12.2f}  {e2e:10.1f}")

print()
print("  Expected: TTFT scales with prompt (prefill is O(T²));")
print("            TPOT roughly constant (one decode step per token)")

# ── Sweep output length, fixed prompt length ───────────────────────────────────
PROMPT_LEN  = 16
OUTPUT_LENS = [8, 16, 32, 64]

print()
print("=" * 60)
print("TPOT vs Output Length  (prompt fixed at", PROMPT_LEN, "tokens)")
print("=" * 60)
print(f"  {'Output':>8}  {'TTFT (ms)':>12}  {'TPOT (ms)':>12}  {'E2E (ms)':>10}")
print(f"  {'-'*50}")

for ol in OUTPUT_LENS:
    ttft, tpot = measure_one(PROMPT_LEN, ol)
    e2e = ttft + tpot * (ol - 1)
    print(f"  {ol:8d}  {ttft:12.1f}  {tpot:12.2f}  {e2e:10.1f}")

print()
print("  Expected: TTFT constant (same prompt); TPOT roughly constant;")
print("            E2E scales linearly with output length")
